login: &login
  adapter: mysql
  host: localhost
  username: root
  password: 123456


development:
  database: auth_dev
  <<: *login

test:
  database: auth_test
  <<: *login

production:
  database: auth_pro
  <<: *login
